# Generated by Django 4.2.4 on 2024-06-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('program', models.CharField(max_length=30)),
                ('studclass', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('teachername', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studname', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('studic', models.CharField(max_length=20)),
                ('studage', models.PositiveIntegerField(default=2)),
                ('housenum', models.CharField(max_length=15)),
                ('mobilenum', models.CharField(max_length=15)),
                ('parentsnum', models.CharField(max_length=15)),
                ('houseaddress', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('currentschool', models.CharField(max_length=100)),
                ('standard', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('studclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmugemilang.admin')),
                ('studname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmugemilang.student')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='studname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmugemilang.student'),
        ),
    ]
