# Generated by Django 4.2.4 on 2024-06-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmugemilang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
