# Generated by Django 4.2.4 on 2024-06-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmugemilang', '0002_student_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='ilmugemilang.subject'),
        ),
    ]
