# Generated by Django 4.2.4 on 2024-06-16 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilmugemilang', '0003_subject_remove_student_subject_student_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('studclass', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('teachername', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='studclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmugemilang.class'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
