# Generated by Django 4.2.4 on 2024-06-18 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilmugemilang', '0006_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmugemilang.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmugemilang.student')),
            ],
        ),
    ]
